version: '3'
services:
  coronavirus-visualization:
    image: coronavirus-covid-19-visualization-prediction:latest
    ports:
      - 8888:8888
    volumes:
      - ./src:/app/src
    command: bash -c "poetry run jupyter lab --ip=0.0.0.0 --no-browser --allow-root"